---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 2343}]
    - ["private_network", {ip: "192.168.33.107"}]
  customize:
    memory: 2096

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[aura-cookbook::default]
    attributes:
