name 'aura-cookbook'
maintainer 'Jose M. Tobar'
maintainer_email 'ilovemysillybanana@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures Aura Mabinogi Server as well as the necessary components.'
long_description 'Installs/Configures Aura Mabinogi Server as well as the necessary components.'
version '0.1.0'
